config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/home", to: 'static_pages#home'
  root to: 'static_pages#home'
  resources :blogs, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

	def index

	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/blogs/index.html.erb
Blog

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manila Mobile Bar Draft</title>
    <%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div id="home-anchor" class="main-page-wrapper">
	<div class="background-picture-container">
		
	</div>
	<div class="container-space">
		
	</div>
	<div id ="fixed-header" class="container-fluid fixed-header">
		<div class="row top-section">
			<div class="follow-us col-md-4 col-md-offset-8">
				<span class="follow-us-text">Follow Us:</span>
				<ul class="social-icons">
					<li><a href="#" class="facebook-icon"></a></li>
					<li><a href="#" class="twitter-icon"></a></li>
				</ul>
			</div>
		</div>
		<div class="row bottom-section">
			<div class="website-logo-container col-xs-12 col-md-4">
				<span class="website-logo">Place Logo Here</span>	
			</div>
			<div class="navigation-header-container col-xs-12 col-md-8">
				<ul class="nav-list">
					<li><a href="#home-anchor">HOME</a></li>
					<li><a href="#ourstory-anchor">OUR STORY</a></li>
					<li><a href="#contact-us-anchor">CONTACT US</a></li>
					<li><%= link_to "BLOGS", blogs_path %></li>
					<li><a href="#">FAQs</a></li>
				</ul>
			</div>
		</div>
	</div>

	<div class="container-fluid video-info-container">
		<div class="row container-header"></div>
		<div class="row main-info-container">
			<div class="col-xs-11 col-md-6 homepage-video-container padding-zero embed-responsive embed-responsive-16by9">
				<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/cAFV_D2baPg" frameborder ="0" allowfullscreen></iframe>
			</div>
			<div class="col-md-4">
				<div class="our-story-title-container">
					<span id="ourstory-anchor" class="text-content-title">Our Story Title Here</span>
				</div>
				<div class="our-story-description-container">
					<span class="text-content">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span>
				</div>
			</div>
		</div>
		<div class="row home-page-pictures-container">
			<div class="col-xs-2 col-xs-offset-1 col-md-2 col-md-offset-1 thumbnail-teasers">
				<%= image_tag("bar.jpg", id: "img1", class:"img-responsive img-thumbnail") %>
			</div>
			<div class="col-xs-2 col-md-2 thumbnail-teasers">
				<%= image_tag("glasses-stock.jpeg", id: "img2", class:"img-thumbnail") %>
			</div>
			<div class="col-xs-2 col-md-2 thumbnail-teasers">
				<%= image_tag("glasses-stock.jpeg", id: "img3",  class:"img-thumbnail") %>
			</div>
			<div class="col-xs-2 col-md-2 thumbnail-teasers">
				<%= image_tag("glasses-stock.jpeg", id: "img4",  class:"img-thumbnail") %>
			</div>
			<div class="col-xs-2 col-md-2 thumbnail-teasers">
				<%= image_tag("glasses-stock.jpeg", id: "img5",  class:"img-thumbnail") %>
			</div>
			<div class="col-xs-1 col-md-1"></div>

			<div id="modal" class="modal-container">
				<span class="close">&times;</span>
				<img id="img-modal" class="modal-content">
				<div id="caption"></div>
			</div>
		</div>
		<div class="row container-footer"></div>
	</div>

	<div class="container-fluid contact-us-container">
		<div class="row">
			<div class="col-xs-12 col-md-4 col-md-offset-4">
				<h1 id="contact-us-anchor">CONTACT US</h1>
				<p>Contact Company Name</p>
				<div class="row">
					<div class="col-xs-12 col-md-3">
						<%= image_tag("contact-icon.png", class:"img-thumbnail img-contact") %>
					</div>
					<div class="col-xs-12 col-md-4">
						<h4>PHILIPPINES</h4>
						<span>xxxxxxx-111</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="container-fluid main-footer">
	<div class="row">
		<div class="copyright-content-container col-xs-12 col-md-4">
			<span>Copyright - Company Name</span>
		</div>
		<div class="col-xs-12 col-md-5">
			<ul>
				<li><a href="#home-anchor">HOME</a></li>
				<li><a href="#ourstory-anchor">OUR STORY</a></li>
				<li><a href="#contact-us-anchor">CONTACT US</a></li>
				<li><a href="#">BLOGS</a></li>
				<li><a href="#">FAQS</a></li>
			</ul>
		</div>
	</div>
</div>